[build]
  publish = "."
  functions = "netlify/functions"
  command = "cd netlify/functions && npm install"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
